export const offices = [
  {
    id: 1,
    country_id: 185,
    title: "Abu dhabi",
    phone: "638-757-8582",
    contact: "MIchael Malki",
  },
  {
    id: 3,
    country_id: 52,
    title: "Cairo",
    phone: "252-224-8525",
    contact: "David Johns",
  },
  {
    id: 4,
    country_id: 13,
    title: "Bahrain",
    phone: "542-227-5825",
    contact: "Katie Ballmer",
  },
  {
    id: 5,
    country_id: 142,
    title: "Doha",
    phone: "758-278-9597",
    contact: "Ariel Levy",
  },
  {
    id: 6,
    country_id: 152,
    title: "Riyadh",
    phone: "285-285-1474",
    contact: "Andrew Hobart",
  },
];

export const users = [
  {
    id: 1,
    office_id: 1,
    role_id: 1,
    email: "j.doe@amonic.com",
    first_name: "John",
    last_name: "Doe",
    birthday: "1983-01-13T00:00:00Z",
    active: true,
  },
  {
    id: 2,
    office_id: 1,
    role_id: 2,
    email: "k.omar@amonic.com",
    first_name: "Karim",
    last_name: "Omar",
    birthday: "1980-03-19T00:00:00Z",
    active: true,
  },
  {
    id: 3,
    office_id: 3,
    role_id: 2,
    email: "h.saeed@amonic.com",
    first_name: "Hannan",
    last_name: "Saeed",
    birthday: "1989-12-20T00:00:00Z",
    active: true,
  },
  {
    id: 4,
    office_id: 6,
    role_id: 2,
    email: "a.hobart@amonic.com",
    first_name: "Andrew",
    last_name: "Hobart",
    birthday: "1990-01-30T00:00:00Z",
    active: true,
  },
  {
    id: 5,
    office_id: 5,
    role_id: 2,
    email: "k.anderson@amonic.com",
    first_name: "Katrin",
    last_name: "Anderson",
    birthday: "1992-11-10T00:00:00Z",
    active: true,
  },
  {
    id: 6,
    office_id: 1,
    role_id: 2,
    email: "h.wyrick@amonic.com",
    first_name: "Hava",
    last_name: "Wyrick",
    birthday: "1988-08-08T00:00:00Z",
    active: true,
  },
  {
    id: 7,
    office_id: 4,
    role_id: 2,
    email: "marie.horn@amonic.com",
    first_name: "Marie",
    last_name: "Horn",
    birthday: "1981-04-06T00:00:00Z",
    active: true,
  },
  {
    id: 8,
    office_id: 1,
    role_id: 2,
    email: "m.osteen@amonic.com",
    first_name: "Milagros",
    last_name: "Osteen",
    birthday: "1991-02-03T00:00:00Z",
    active: false,
  },
];
