services:
  postgres:
    image: postgres:latest
    container_name: auth_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5430:5432
    volumes:
      - ./storage/database/:/var/lib/postgresql/data/pgdata
    networks:
      - database

  adminer:
    image: adminer
    container_name: auth_adminer
    restart: always
    ports:
      - 5440:8080
    depends_on:
      - postgres
    networks:
      - database

networks:
  database:
    driver: bridge
