services:
  mysql:
    image: mysql:8.0
    container_name: auth_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: airplanes
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - ./storage/database/:/var/lib/mysql/
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - database

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "5043:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
    volumes:
      - ./api:/swagger

networks:
  database:
    driver: bridge
